// @ts-expect-error Generated by the OpenNext build before Wrangler runs.
import handler from "./.open-next/worker.js";

export { RevisionReplayLedger } from "./src/server/modelduel/revision-replay-do";

export default {
  fetch: handler.fetch,
} satisfies ExportedHandler<CloudflareEnv>;
